# This workflow will make a static code analysis using the codacy tool

name: Codacy Analysis

on:
  push:
    branches: [master, dev]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@master
